# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv0001
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 10Gi
#   hostPath:
#     path: /data/pv0001/
# ---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    clusters:
      - name: "simple"
    users:
      test_user/password_sha256_hex: 10a6e6cc8311a3e2bcc09bf6c199adecd5dd59408c343e926b129c4914f3cb01
      test_user/networks/ip:
        - 0.0.0.0/0
  templates:
    volumeClaimTemplates:
    - name: data-volume-template
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - name: log-volume-template
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi